### ISSUE TITLE
99q2

### ISSUE THREAD

**Issue by K3nnysCMD** [supern64/PlaceMC#1]
HI you just talked to me a few mins ago i have imported the plugin May you please contact me on discord Kenny#1125 so i know what i do 
Thanks,
Kenny

**Comment by supern64** [comment]
Do you have a world already set up that you want to use this on?

**Comment by K3nnysCMD** [comment]
yeah

**Comment by K3nnysCMD** [comment]
Please reach out to me on discord Kenny#1125 Thanks

**Comment by K3nnysCMD** [comment]
dont you remember im the person whose server you join and was looking to build a minecraft version of place

**Comment by supern64** [comment]
I certainly don't fully remember it, did someone else introduce me to you?

**Comment by K3nnysCMD** [comment]
no you just joined my server

**Comment by K3nnysCMD** [comment]
but may you add me on discord

**Comment by K3nnysCMD** [comment]
to assist me further

**Comment by K3nnysCMD** [comment]
or just join the server Kennyco.minefort.com

**Comment by supern64** [comment]
alright

**Comment by supern64** [comment]
resolved through discord
